#!/bin/bash

set -e

__dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "${__dir}"


# # # # # # # # # # # # # # # # # # # # #
# Load projectname from .projectname file
PROJECTNAME=$(head -n 1 .projectname)
#
# # # # # # # # # # # # # # # # # # # # #

# # # # # #
# Run synx
./scripts/run_synx "$PROJECTNAME"
#
# # # # # #

# # # # # # #
# Run xUnique
./scripts/run_xUnique "$PROJECTNAME"
#
# # # # # # #
