
name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: macos-10.15
    env:
      DEVELOPER_DIR: /Applications/Xcode_12.4.app/Contents/Developer
      # To create a fresh cache if none of the cache parameters has changed,
      # simply bump the CACHE_VERSION variable. This is mainly needed when
      # changes to the caching steps have been made, but might be useful for
      # other debugging purposes as well. Github deletes the oldest unused
      # the volume of caches increases over a certain value
      CACHE_VERSION: 1
      BUNDLER_VERSION: 2.2.29

    steps:
    - name: Create output directories
      run: |
        _BUILD_OUTPUT_DIR=$HOME/build_output
        mkdir $_BUILD_OUTPUT_DIR
        echo "BUILD_OUTPUT_DIR=$_BUILD_OUTPUT_DIR" >> $GITHUB_ENV
        
        _XCODEBUILD_LOG_DIR=$_BUILD_OUTPUT_DIR/xcodebuild_logs
        mkdir $_XCODEBUILD_LOG_DIR
        echo "XCODEBUILD_LOG_DIR=$_XCODEBUILD_LOG_DIR" >> $GITHUB_ENV
    
    - name: 'Checkout code'
      uses: actions/checkout@v2
    
    - name: 'Setup ruby'
      uses: ruby/setup-ruby@v1
      with:
        bundler: ${{ env.BUNDLER_VERSION }}
        bundler-cache: true
    
    - name: 'Fetch pod cache'
      id: pod-cache
      uses: actions/cache@v1
      with:
        path: ./Pods
        key: cache-${{ env.CACHE_VERSION }}_bundle-${{ hashFiles('Podfile.lock') }}
        
    - name: 'Install pods'
      if: steps.pod-cache.outputs.cache-hit != 'true'
      run: |
        bundle exec pod install

    - name: 'Clean / Build / Test'
      run: |
        xcodebuild \
          -workspace WebCredentials.xcworkspace \
          -scheme "WebCredentials" \
          -destination 'platform=iOS Simulator,name=iPad Air (3rd generation),OS=latest' \
          clean build \
          | tee "$XCODEBUILD_LOG_DIR/xcodebuild-verbose.log" \
          | bundle exec xcpretty \
          | tee "$XCODEBUILD_LOG_DIR/xcodebuild-xcpretty.log"

    - name: 'Upload xcodebuild logs'
      uses: actions/upload-artifact@v1
      with:
        name: xcodebuild-logs
        path: ${{ env.XCODEBUILD_LOG_DIR }}



